spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trade?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: 'Q!W@E#R$T%'
  redis:
    redisson:
      file: classpath:redisson.yml

server:
  port: 8080





TIME-ZONE: GMT+8