DROP TABLE IF EXISTS entrusted_order;
CREATE TABLE entrusted_order (
  `id` VARCHAR(32) NOT NULL PRIMARY KEY,
   `trade_no` VARCHAR(100) NULL COMMENT '委託交易號',
  `vendor_id` VARCHAR(32) NOT NULL COMMENT '廠商id',
  `stock_id` VARCHAR(32) NOT NULL COMMENT '股票id',
  `user_account_number` VARCHAR(20) NOT NULL COMMENT 'user 證券帳號',
  `user_name` VARCHAR(32) NOT NULL COMMENT 'user 名字',
  `trade_type` TINYINT NOT NULL COMMENT '股票委託交易類型:0整股、1盤後、2盤後零股',
  `stock_type` TINYINT NOT NULL COMMENT '股票委託種類:0現股1融資2融券',
  `stock_condition` TINYINT NOT NULL COMMENT '股票委託條件:0ROD、1IOC、2FOK',
  `price_type` TINYINT NOT NULL COMMENT '股票委託價格類別:0限價、1市價',
  `status` TINYINT NOT NULL COMMENT '股票委託狀態:0預約中、1委託成功、2全部成交、3改量、4改價、-1刪單、-2委託失敗',
  `business` TINYINT NOT NULL COMMENT '商業條件:0賣、1買',
  `entrusted_qty` INT NOT NULL COMMENT '委託數量',
  `traded_qty` INT NULL COMMENT '成交數量',
  `canceled_qty` INT NULL COMMENT '取消數量',
  `entrusted_price` DECIMAL NOT NULL COMMENT '委託金額',
  `traded_price` DECIMAL NULL COMMENT '成交價格',
  `fee` DECIMAL NULL COMMENT '成交手續費',
  `processor` VARCHAR(50) NULL COMMENT '執行緒id',
  `remark` VARCHAR(200) NULL COMMENT '備註',
  `entrusted_timestamp` BIGINT NOT NULL COMMENT '委託日期時間TIMESTAMP',
  `traded_timestamp` BIGINT NULL COMMENT '成交日期時間TIMESTAMP',
  `canceled_timestamp` BIGINT NULL COMMENT '取消日期時間TIMESTAMP',
  `created_timestamp` BIGINT NOT NULL COMMENT '建立日期時間TIMESTAMP',
  `update_timestamp` BIGINT NULL COMMENT '更新時間TIMESTAMP',
  `created_user` VARCHAR(32) NOT NULL COMMENT '建立人員',
  `updated_user` VARCHAR(32)NULL COMMENT '修改人員');